# Generated by Django 4.2.3 on 2023-07-11 15:37

from django.db import migrations, models
import petstagram.photos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='mediafiles/pet_photos', validators=[petstagram.photos.validators.validate_file_less_than_5mb]),
        ),
    ]
